[[redirects]]
  from = "https://heictojpgpro.netlify.app/*"
  to = "https://heictojpgpro.com/:splat"
  status = 301
  force = true
  
[[redirects]]
  from = "https://heictojpgpro.com/*"
  to = "/index.html"
  status = 200
