[[redirects]]
  from = "https://swp-calculator.netlify.app"
  to = "https://swp-calculator.mutualfundjournal.in/"
  status = 301
  force = true
[[redirects]]
  from = "https://swp-calculator.mutualfundjournal.in/*"
  to = "/index.html"
  status = 200
