[[redirects]]
  from = "https://lumpsum-calculator-production.netlify.app/*"
  to = "https://lumpsum-calculator.mutualfundjournal.in/:splat"
  status = 301
  force = true
  
[[redirects]]
  from = "https://lumpsum-calculator.mutualfundjournal.in/*"
  to = "/index.html"
  status = 200