[[redirects]]
  from = "/*"
  to = "https://swp-calculator.mutualfundjournal.in/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/index.html"
  to = "/"
  status = 200

[[redirects]]
  from = "/404"
  to = "/index.html"
  status = 200
