[[redirects]]
  from = "https://clipboard-to-image.netlify.app/*"
  to = "https://clipboard-to-image.toolyoulove.com/:splat"
  status = 301
  force = true
  
[[redirects]]
  from = "https://clipboard-to-image.toolyoulove.com/*"
  to = "/index.html"
  status = 200
